export default function Comment(props) {
  return (
    <div
      className='
                flex
                flex-col
                w-100
                h-fit
                p-1
                m-2
                z-[4]
        '>
      <div
        className='
                w-100
                h-fit
                text-sm
                text-gray-600
                '>
        {props.user}
      </div>
      <div
        className='
                w-100
                h-fit
                text-base
                '>
        {props.cmt}
      </div>
    </div>
  );
}
